version: '3.7'

services:

  bikeshare-catalogue.1.service:
    build: .
    ports:
    - 8080:8080
    environment:
      KUMULUZEE_SERVER_BASEURL: http://bikeshare-catalogue.1.service:8080
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://bikeshare-catalogue.db:5432/bikeshare-catalogue
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL: http://etcd:2379/health
    depends_on:
    - bikeshare-catalogue.db
    - etcd

  bikeshare-catalogue.2.service:
    build: .
    ports:
    - 8081:8080
    environment:
      KUMULUZEE_SERVER_BASEURL: http://bikeshare-catalogue.1.service:8080
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://bikeshare-catalogue.db:5432/bikeshare-catalogue
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL: http://etcd:2379/health
    depends_on:
    - bikeshare-catalogue.db
    - etcd

  bikeshare-catalogue.db:
    image: postgres:alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikeshare-catalogue

  etcd:
    image: quay.io/coreos/etcd
    ports:
    - 2379:2379
    command: >-
      /usr/local/bin/etcd
      -name node1
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster node1=http://etcd:2380
      -cors="*"

  bikeshare-rental.service:
    build: ../bikeshare-rental
    environment:
      KUMULUZEE_SERVER_BASEURL: http://bikeshare-rental.service:8080
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://bikeshare-rental.db:5432/bikeshare-rental
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL: http://etcd:2379/health
    depends_on:
    - bikeshare-rental.db
    - etcd

  bikeshare-rental.db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikeshare-rental
