version: '3.7'

services:
  bikeshare-catalogue.db:
    image: postgres:alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikeshare-catalogue

networks:
  default:
    external:
      name: bikeshare
