apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - image: jboss/keycloak:4.7.0.Final
        name: keycloak
        env:
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-user-pass
              key: keycloak-user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-user-pass
              key: keycloak-password
        - name: DB_VENDOR
          value: h2

        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        volumeMounts:
        - mountPath: /etcd-data
          name: etcddata

      volumes:
      - name: etcddata
        emptyDir: {}

---


apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31007
  selector:
    app: keycloak
